### ISSUE TITLE
Random category

### ISSUE THREAD

**Issue by fwenzel** [kesne/jeopardy-bot#101]
`random for 200` should do exactly that

**Comment by kesne** [comment]
What happens when a category has the word "random" in the string? Do we just prefer matching `random` over matching a category.

**Comment by fwenzel** [comment]
yeah I considered that. not sure what the best solution is

**Comment by kesne** [comment]
I guess if it's documented, then it shouldn't matter, because you'll type more of the category if you want to not use the random behavior..

Unless you hit a category with the literal name `random`, then we're hosed.

**Comment by fwenzel** [comment]
well there might be ways to make disambiguate in that edge case.

**Comment by kesne** [comment]
I agree. Just not sure what it is exactly.

**Comment by kesne** [comment]
How much sense does it make to have a value along with the `random` selection? I guess supporting both `random category` and `random category for 200` might make sense?

**Comment by fwenzel** [comment]
yeah definitely include the value just like any other selection. Though I admit, that means you can only select randomly between the categories that have this value available.

**Comment by kesne** [comment]
Okay then I think this shouldn't be too bad. It has the potential to break when a category is literally `random` though. What if we use the new `gimme` command. So `gimme category` gives you that category at the lowest value, and `gimme for 200` gives you a random category for that value?

**Comment by fwenzel** [comment]
I like the `gimme` command.

`gimme` would give you the lowest value for a random category.
`gimme category` gives you the lowest value for that category.

Optional:
`gimme for 200` gives you a random category for 200, so long as that exists.

**Comment by kesne** [comment]
Sweet, I'll implement it like that then. I'm happy with it.

**Comment by kesne** [comment]
In master.
