### ISSUE TITLE
"when" is an undocumented keyword

### ISSUE THREAD

**Issue by fwenzel** [kesne/jeopardy-bot#103]
`when` starts a solution but that's not in the help.

Either it should not be a valid question or it should be documented.

**Comment by kesne** [comment]
Yeah we probably should update the help. At some point I wanted it to be auto-generated, but I think that's probably not going to happen.

**Comment by kesne** [comment]
Documented it in master under the new trebek module.

**Comment by fwenzel** [comment]
Fun fact if you push a commit that says `fix #103` in the commit message, github will close this automatically.

**Comment by kesne** [comment]
I know, I just very infrequently sync my commits up with the issues. It's much less planned than that.
