### ISSUE TITLE
single letter responses behave oddly

### ISSUE THREAD

**Issue by fwenzel** [kesne/jeopardy-bot#104]
`what is f` does not match when `F` is expected. Not sure why this is case sensitive? That seems unnecessary.

**Comment by kesne** [comment]
What's nice about this is that our auto-challenge stuff will catch these cases. But it would be nice if it didn't happen in the first place.

I can confirm this is still occurring in the new trebek module, and is reproducible.

**Comment by kesne** [comment]
Fixed in master. the dice coefficient didn't know what to do with single-character guesses. I added a string comparison to check if the strings are exactly the same, which it will be in single-character cases.
