### ISSUE TITLE
Add a screenshot of gameplay. 

### ISSUE THREAD

**Issue by eltonjuan** [kesne/jeopardy-bot#134]
When considering the vast landscape of Jeopardy! bots in Slack, it is important for one Jeopardy bot to stand out among the rest. Without a screenshot, it's hard to see just how awesome this Jeopardy bot is. It  might be helpful to include a screenshot of gameplay so that people who might stumble across this repo. get an idea of what jeopardy-bot has to offer.

**Comment by kesne** [comment]
The entire readme need a rewrite. I'm hoping to get some images up once the admin panel is completed.

**Comment by kesne** [comment]
<img width="383" alt="screen shot 2016-01-12 at 12 38 54 am" src="https://cloud.githubusercontent.com/assets/498479/12258692/53cc6cfe-b8c5-11e5-9b14-5b642f3abb80.png">

There's a big image.

**Comment by kesne** [comment]
Without the time: 
![ss2](https://cloud.githubusercontent.com/assets/498479/12258733/9edc2464-b8c5-11e5-8703-3187ced93f15.png)

**Comment by kesne** [comment]
In master. Also will be made better with #160.
