### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by kesne** [kesne/jeopardy-bot#142]
We really need to add migrations so that when other people deploy, we don't always break their deploy by changing what the db fields are.

**Comment by kesne** [comment]
We probably need this for 1.0. I think it would be ideal to make this as simple as possible (automatic on startup, even?).

**Comment by pstephenson02** [comment]
https://github.com/db-migrate/node-db-migrate - This looks like maybe one of the most popular options.

There are a couple that are specific to mongoose, but they don't look widely used:
https://github.com/madhums/mongoose-migrate
https://github.com/flashstockinc/mongoose-data-migrate
