### ISSUE TITLE
Failed to compile Cairo app on Heroku

### ISSUE THREAD

**Issue by johnbocalig** [kesne/jeopardy-bot#189]
-----> Cairo app detected
-----> Vendoring binaries
       Fetching https://s3.amazonaws.com/mojodna-heroku/heroku-16/cairo-1.14.6-1.tar.gz
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
 !     Push rejected, failed to compile Cairo app.
 !     Push failed

**Comment by kpeatt** [comment]
I was able to fix this by using: https://github.com/sky-uk/heroku-buildpack-cairo instead.
