### ISSUE TITLE
Trigger async rendering of next board while playing previous board

### ISSUE THREAD

**Issue by fwenzel** [kesne/jeopardy-bot#207]
Takes a long time from answering to choosing again. If it is rendering delay (not: upload to slack), we should kick off rendering when the previous question was chosen (since the next state is already clear)

**Comment by kesne** [comment]
It's uploading to slack that's causing the delay unfortunately :(

We used to upload images to imgur and let unfurl take care of it, but that didn't seem super ideal. I can offer that again as an option to speed up some instances though.

**Comment by fwenzel** [comment]
Makes sense -- clearly this thing needs upload to S3 and a CDN 😆
