### ISSUE TITLE
Continuous Deployment to DigitalOcean

### ISSUE THREAD

**Issue by cpeddecord** [kesne/jeopardy-bot#38]

**Comment by kesne** [comment]
We're going to have a "deploy to heroku" button in the readme, but it might also be useful to have instructions on how we do DO deployment in the readme as well.

**Comment by kesne** [comment]
@cpeddecord Should this be tracked here?

**Comment by kesne** [comment]
@cpeddecord Here's what I think we should do:

You add a page to the wiki on how to set up the bot for Digital Ocean (basics).

Setting up CD for most people won't matter. It's only for our case where we're building it, testing it, and using it all in one slack team.

**Comment by kesne** [comment]
No progress so I'm closing this out.
