### ISSUE TITLE
Dates should be exact dates

### ISSUE THREAD

**Issue by JasonVeselka** [kesne/jeopardy-bot#43]
For example, the question was:
"The U.S. declared war on Japan on this Monday in 1941"
In which a contestant answered:
"december 5th"
And Jeopardy Bot said this was correct.
Dates should be exact at least by month(could be spelled wrong) and actual date in this case it should have been 8.

**Comment by kesne** [comment]
Probably just use moment to try to parse the answer. If it parses (`moment(answer).isValid() === true`), consider it a date. If it's a date, use the `moment#isSame` method to compare them. That should handle just about everything we care about.

This will also work for years, where our string comparison might fail.

**Comment by kesne** [comment]
Fixed in master.
