### ISSUE TITLE
Date parsing is too aggresive

### ISSUE THREAD

**Issue by JasonVeselka** [kesne/jeopardy-bot#56]
While playing the game we ran into a question that could have been answered with a 2 but the answer only allowed for II(two i's). Should probably support both answers.

**Comment by kesne** [comment]
Our string similarity should have caught this case... Interesting that it didn't. Maybe something was mistaken for a date?

**Comment by JasonVeselka** [comment]
Could be true. The date stuff couldn't really be tested...
:)

**Comment by kesne** [comment]
I mean you can isolate the case to this:

``` javascript
moment('World War 2').isValid();
```

Which returns true. Which is bad.

**Comment by kesne** [comment]
I just changed the date parsing to use a new module that should hopefully help us catch the date edge cases. I also added a new number matcher so that we do strict matching on numbers. This will catch the case for year-only answers.

Going to keep this open until we see things resolve in real use.

**Comment by kesne** [comment]
Looks to be fixed.
