### ISSUE TITLE
Show value of daily double

### ISSUE THREAD

**Issue by kesne** [kesne/jeopardy-bot#89]

**Comment by ljharb** [comment]
Also my current score, so I know what my options are

**Comment by kesne** [comment]
Maybe like...

> What would you like to wager? (max of $1000, min of $5)

**Comment by kesne** [comment]
Or we could show you score, and also show the same category selection message as before (might be helpful).

> Ok, `Category` for `$xxx`
> Answer: Daily Double
> Your score is $1000. What would you like to wager? (max of $1000, min of $5)

**Comment by ljharb** [comment]
Looks great

**Comment by kesne** [comment]
Implemented in master.
