### ISSUE TITLE
Issues with quotes in category titles

### ISSUE THREAD

**Issue by fwenzel** [kesne/jeopardy-bot#95]
Categories are sometimes:
`"EE"`
`"SA"`.

They are hard to select.
- `EE for 200` won't be accepted
- `“SA” for 200` (smart quotes) won't be accepted

The matcher should probably remove quotes on both ends (user input and categories) to determine similarity.

**Comment by fwenzel** [comment]
@emroot

**Comment by kesne** [comment]
Yeah good call. I think this can be fixed with the next "trebek" module (#79).

**Comment by kesne** [comment]
Fixed in master.
