### ISSUE TITLE
"Seen here"

### ISSUE THREAD

**Issue by fwenzel** [kesne/jeopardy-bot#96]
These questions are virtually always useless -- but no idea what to do with them instead?

**Comment by kesne** [comment]
My idea was to drop the timeout on these question to 1/2 of what it is normally at. I'm not sure "seen here" is 100% an indicator bad questions, so I'm hesitant to completely remove them.

In the future, when we build "incomplete games" (i.e. games that start with missing questions) we could just flag these questions as invalid and just have them removed when you start the game.

**Comment by kesne** [comment]
Related #111

**Comment by kesne** [comment]
This will be done for #111.
